import {z} from 'zod';
import {canEdit} from '@/lib/access';
import {api,db,json,body,HttpError,bucket} from '@/lib/server';
import {entryInput} from '@/lib/v5-models';
import {allEntries,entryById,entryKey,validateReferences} from '@/lib/v5-server';
export const GET=api(async req=>json({entries:(await allEntries()).filter(e=>canEdit(req)||e.kind!=='capsule'||e.data.stage!=='draft')}));
export const POST=api(async req=>{const raw=await body(req),v=entryInput.parse(raw);const existing=await entryById(v.id,false);if(existing){if(existing.kind!==v.kind||JSON.stringify(existing.data)!==JSON.stringify(v.data))throw new HttpError(409,'This item was already saved with different details. Refresh before editing.');return json({entry:await entryById(v.id),duplicate:true});}await validateReferences(v);const key=entryKey(v);if(key&&await db().prepare('SELECT id FROM entries WHERE dedupe_key=?').bind(key).first())throw new HttpError(409,'This choice changed elsewhere. Refresh and try again.');const now=new Date().toISOString();
 if(raw.completeWish&&v.kind==='memory'&&v.data.wishId){const rev=z.number().int().nonnegative().parse(raw.wishRevision);const wish=await db().prepare('SELECT revision FROM wishes WHERE id=?').bind(v.data.wishId).first<{revision:number}>();if(!wish||wish.revision!==rev)throw new HttpError(409,'This wish changed elsewhere. Refresh before completing it.');const res=await db().batch([db().prepare('INSERT INTO entries(id,kind,data,dedupe_key,created_at,updated_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM wishes WHERE id=? AND revision=?)').bind(v.id,v.kind,JSON.stringify(v.data),key,now,now,v.data.wishId,rev),db().prepare("UPDATE wishes SET status='Done',updated_at=?,revision=revision+1 WHERE id=? AND revision=? AND EXISTS(SELECT 1 FROM entries WHERE id=?)").bind(now,v.data.wishId,rev,v.id)]);if(!res[0].meta.changes)throw new HttpError(409,'This wish changed elsewhere. Please refresh.');}
 else await db().prepare('INSERT INTO entries(id,kind,data,dedupe_key,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(v.id,v.kind,JSON.stringify(v.data),key,now,now).run();return json({entry:await entryById(v.id)},201);});
export const PATCH=api(async req=>{const raw=await body(req),v=entryInput.parse(raw),rev=z.number().int().nonnegative().parse(raw.revision);const current=await entryById(v.id,false);if(!current)throw new HttpError(404,'This item no longer exists.');if(current.kind!==v.kind)throw new HttpError(400,'An item cannot change its type.');if(current.kind==='capsule'&&current.data.stage==='sealed')throw new HttpError(409,'Sealed letters cannot be rewritten. Create a new letter instead.');if(entryKey(current)!==entryKey(v))throw new HttpError(400,'The person and linked item cannot change.');await validateReferences(v);const r=await db().prepare('UPDATE entries SET data=?,updated_at=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(v.data),new Date().toISOString(),v.id,rev).run();if(!r.meta.changes)throw new HttpError(409,'This item changed elsewhere. Refresh before saving.');return json({entry:await entryById(v.id)});});
export const DELETE=api(async req=>{const {id,revision}=z.object({id:z.string().uuid(),revision:z.number().int().nonnegative()}).parse(await body(req));const e=await entryById(id);if(!e||e.revision!==revision)throw new HttpError(409,'This item changed elsewhere. Please refresh.');const removed=await db().prepare('DELETE FROM entries WHERE id=? AND revision=?').bind(id,revision).run();if(!removed.meta.changes)throw new HttpError(409,'Please refresh before removing this item.');if(e.kind==='capsule'){const assets=(await db().prepare("SELECT object_key FROM assets WHERE parent_type='capsule' AND parent_id=?").bind(id).all<{object_key:string}>()).results;await db().prepare("DELETE FROM assets WHERE parent_type='capsule' AND parent_id=?").bind(id).run();for(const a of assets)await bucket().delete(a.object_key);}return json({ok:true});});
