"use client";
import {EditButton} from "./gift-access";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Upload,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {toast} from 'sonner';
import {Asset,people} from '@/lib/v5-models';
import {uploadAsset,useAssets} from '@/lib/v5-client';
import {request} from '@/lib/wish-drafts';
import {Choice,Confirm} from './gift-controls';
export default function AudioNotes({parentType,parentId,readOnly=false,onBusyChange}:{parentType:Asset['parentType'];parentId:string;readOnly?:boolean;onBusyChange?:(v:boolean)=>void}){
 const {assets,error,refresh}=useAssets(parentId),[person,setPerson]=useState('Yuliya'),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[preview,setPreview]=useState<Blob|null>(null),[url,setUrl]=useState(''),[removing,setRemoving]=useState<Asset|null>(null);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),fileInput=useRef<HTMLInputElement>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(!preview){setUrl('');return;}const object=URL.createObjectURL(preview);setUrl(object);return()=>URL.revokeObjectURL(object);},[preview]);
 useEffect(()=>{if(!recording)return;const t=setInterval(()=>setSeconds(s=>{if(s>=119){recorder.current?.stop();return 120;}return s+1;}),1000);return()=>clearInterval(t);},[recording]);
 async function start(){if(busy||recording)return;setBusy(true);try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Recording is unavailable here. Upload a recording instead.');const tracks=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){tracks.getTracks().forEach(t=>t.stop());return;}stream.current=tracks;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(v=>MediaRecorder.isTypeSupported(v));const mr=new MediaRecorder(tracks,mime?{mimeType:mime}:undefined);recorder.current=mr;chunks.current=[];mr.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);};mr.onstop=()=>{tracks.getTracks().forEach(t=>t.stop());if(alive.current){setRecording(false);setPreview(new Blob(chunks.current,{type:mr.mimeType.split(';')[0]}));}};mr.onerror=()=>{tracks.getTracks().forEach(t=>t.stop());if(alive.current){setRecording(false);toast.error('Recording stopped. Please try again or upload audio.');}};setPreview(null);setSeconds(0);mr.start(1000);setRecording(true);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());toast.error((e as Error).message);}finally{setBusy(false);}}
 async function save(blob:Blob,filename:string){setBusy(true);try{await uploadAsset(blob,filename,parentType,parentId,'voice',person);setPreview(null);await refresh();toast.success('Your voice is kept here.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!removing)return;setBusy(true);try{await request('/api/assets/'+removing.id,{method:'DELETE'});setRemoving(null);await refresh();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{onBusyChange?.(busy||recording||!!preview);},[busy,recording,preview,onBusyChange]);
 const ext=preview?.type.includes('mp4')?'m4a':preview?.type.includes('ogg')?'ogg':'webm';
 return <div className="audio-notes"><h4>Voice letter · 聲音情書</h4>{assets.filter(a=>a.mime.startsWith('audio/')).map(a=><div className="voice-item" key={a.id}><div><p>{a.person} <small>{a.filename}</small></p><audio controls preload="none" src={'/api/assets/'+a.id}/></div>{!readOnly&&<EditButton size="icon" variant="ghost" onClick={()=>setRemoving(a)} aria-label={'Delete '+a.filename}><Trash2 size={16}/></EditButton>}</div>)}{error&&<p className="field-error" role="alert">{error}</p>}{!readOnly&&<><Choice label="Voice of" value={person} options={people} onChange={setPerson} disabled={recording||busy}/><div className="dialog-actions">{recording?<Button onClick={()=>recorder.current?.stop()}><Square size={16}/>Stop · {seconds}s / 120s</Button>:<EditButton variant="outline" onClick={start} disabled={busy}><Mic size={16}/>Record</EditButton>}<EditButton variant="ghost" disabled={busy||recording} onClick={()=>fileInput.current?.click()}><Upload size={16}/>Upload audio</EditButton><input className="sr-only" ref={fileInput} type="file" accept="audio/mpeg,audio/mp4,audio/x-m4a,audio/wav,audio/x-wav,audio/webm,audio/ogg" onChange={e=>{const f=e.target.files?.[0];if(f)save(f,f.name);e.target.value='';}}/></div>{preview&&<div className="recording-preview"><audio controls src={url}/><div className="dialog-actions"><EditButton disabled={busy} onClick={()=>save(preview,`${person}-${new Date().toISOString().slice(0,10)}.${ext}`)}>{busy?'Saving…':'Keep this recording'}</EditButton><Button variant="ghost" disabled={busy} onClick={()=>setPreview(null)}>Discard take</Button></div></div>}<p className="small-meta">Record up to 2 minutes, or upload audio up to 24 MB.</p></>}<Confirm open={!!removing} title="Remove this recording?" description="The saved audio will be deleted." busy={busy} onClose={()=>setRemoving(null)} onConfirm={remove}/></div>;
}
