"use client";
import {EditButton} from "./gift-access";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {people,Entry} from '@/lib/v5-models';
import {saveEntry,useEntries,useAssets} from '@/lib/v5-client';
import {toast} from 'sonner';
import AudioNotes from './audio-notes';
export default function PhotoPerspectives({photoId}:{photoId:string}){const {entries,error}=useEntries(),{assets}=useAssets(photoId);return <div className="photo-extras"><h4>One moment, two hearts · 兩個視角</h4><div className="perspective-pair">{people.map(person=><Perspective key={photoId+person} photoId={photoId} person={person} entry={entries.find(e=>e.kind==='perspective'&&e.data.photoId===photoId&&e.data.person===person)}/>)}</div>{error&&<p className="field-error" role="alert">{error}</p>}{entries.filter(e=>e.kind==='memory'&&e.data.photoIds.includes(photoId)).map(e=>e.kind==='memory'&&<div className="linked-memory" key={e.id}><small>{e.data.wishId?'A wish made real':'From our timeline'} · {e.data.date}</small><p>{e.data.title}</p><p className="quiet">{e.data.notes}</p></div>)}{assets.filter(a=>a.purpose==='original').map(a=><a key={a.id} href={'/api/assets/'+a.id} download={a.filename} className="text-link">Download original HEIC · {a.filename}</a>)}<AudioNotes parentType="photo" parentId={photoId}/></div>;}
function Perspective({photoId,person,entry}:{photoId:string;person:typeof people[number];entry?:Entry}){const [text,setText]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[base,setBase]=useState<Entry|undefined>(entry);useEffect(()=>{if(!dirty){setText(entry?.kind==='perspective'?entry.data.text:'');setBase(entry);}},[entry,dirty]);async function save(){setBusy(true);try{const saved=await saveEntry({id:base?.id||crypto.randomUUID(),kind:'perspective',data:{photoId,person,text}},base);setBase(saved);setDirty(false);toast.success(person+'’s words are saved.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}return <div className="perspective"><label htmlFor={'perspective-'+person}>{person}</label><Textarea id={'perspective-'+person} rows={3} maxLength={2000} value={text} onChange={e=>{setText(e.target.value);setDirty(true);}} placeholder="What I remember feeling…"/><EditButton variant="outline" size="sm" disabled={!dirty||busy} onClick={save}>{busy?'Saving…':'Save words'}</EditButton></div>;}
