"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Sparkles,Plus,Search,ArrowRight,Check,Heart,ExternalLink,Pencil,Trash2,RefreshCw,LoaderCircle,X,Plane,Utensils,Ticket,ShoppingBag,BookOpen,Home} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription,EmptyContent} from '@/components/ui/empty';
import {categories,statuses,priorities,Wish,WishInput,wishInput,duplicateKey} from '@/lib/models';
import {Draft,makeDraft,splitDrafts,request} from '@/lib/wish-drafts';
import {Choice,Field,Confirm} from './gift-controls';
import {toast} from 'sonner';
import {Photo} from '@/lib/models';
import {people} from '@/lib/v5-models';
import {useEntries,saveEntry,announceChange} from '@/lib/v5-client';
import MemoryComposer from './memory-composer';
const icons={Travel:Plane,Food:Utensils,Experiences:Ticket,Things:ShoppingBag,Learning:BookOpen,Everyday:Home,Other:Heart};
export default function Wishes({active,photos,onMemorySaved}:{active:boolean;photos:Photo[];onMemorySaved:()=>void}){
 const {entries,error:entryError,refresh:refreshEntries}=useEntries(active),[collector,setCollector]=useState('Yuliya'),[collection,setCollection]=useState('All'),[completing,setCompleting]=useState<Wish|null>(null),[interestBusy,setInterestBusy]=useState(false);
 const likes=(id:string,p:string)=>entries.some(e=>e.kind==='interest'&&e.data.wishId===id&&e.data.person===p&&e.data.selected);
 useEffect(()=>{try{const p=localStorage.getItem('yc-collector');if(p&&people.includes(p as typeof people[number]))setCollector(p);}catch{}},[]);
 async function toggleInterest(w:Wish){setInterestBusy(true);try{const old=entries.find(e=>e.kind==='interest'&&e.data.wishId===w.id&&e.data.person===collector);await saveEntry({id:old?.id||crypto.randomUUID(),kind:'interest',data:{wishId:w.id,person:collector as typeof people[number],selected:!likes(w.id,collector)}},old);await refreshEntries();}catch(e){toast.error((e as Error).message);await refreshEntries();}finally{setInterestBusy(false);}}

 const [wishes,setWishes]=useState<Wish[]>([]),[loaded,setLoaded]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [raw,setRaw]=useState(''),[drafts,setDrafts]=useState<Draft[]>([]),[review,setReview]=useState(false),[saving,setSaving]=useState(false),[draftError,setDraftError]=useState('');
 const [aiBusy,setAiBusy]=useState(false),[aiStatus,setAiStatus]=useState(''),[aiError,setAiError]=useState(''),[aiApplied,setAiApplied]=useState(false);
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All categories'),[status,setStatus]=useState('All wishes'),[sort,setSort]=useState('Newest');
 const [editing,setEditing]=useState<Wish|null>(null),[editError,setEditError]=useState(''),[removing,setRemoving]=useState<Wish|null>(null);
 const worker=useRef<Worker|null>(null),requesting=useRef(false),draftLoaded=useRef(false);
 const refresh=useCallback(async()=>{if(requesting.current)return;requesting.current=true;setLoading(true);try{const r=await request('/api/wishes');setWishes(r.wishes);setError('');}catch(e){setError((e as Error).message);}finally{setLoaded(true);setLoading(false);requesting.current=false;}},[]);
 useEffect(()=>{if(active&&!loaded)refresh();},[active,loaded,refresh]);
 useEffect(()=>{const focus=()=>{if(active)refresh();};window.addEventListener('focus',focus);window.addEventListener('yc-archive-change',focus);return()=>{window.removeEventListener('focus',focus);window.removeEventListener('yc-archive-change',focus);};},[active,refresh]);
 useEffect(()=>{try{setRaw(localStorage.getItem('yc-wish-draft')||'');}catch{}draftLoaded.current=true;return()=>{worker.current?.terminate();};},[]);
 useEffect(()=>{if(draftLoaded.current)try{if(raw)localStorage.setItem('yc-wish-draft',raw);else localStorage.removeItem('yc-wish-draft');}catch{}},[raw]);
 function prepare(ai=false){setDraftError('');setAiError('');setAiApplied(false);try{const list=splitDrafts(raw,wishes);if(!list.length){setDraftError('Write a wish first, or add a blank card.');return;}setDrafts(list);setReview(true);if(ai)organise(list);}catch(e){setDraftError((e as Error).message);}}
 function organise(list:Draft[]=drafts){if(aiBusy||!list.length)return;setAiBusy(true);setAiError('');setAiStatus('Starting the on-device language model…');if(!worker.current)worker.current=new Worker('/wish-ai.worker.js',{type:'module'});
  worker.current.onmessage=({data})=>{if(data.type==='status')setAiStatus(data.message);if(data.type==='error'){setAiError(data.message);setAiBusy(false);worker.current?.terminate();worker.current=null;}if(data.type==='result'){setDrafts(current=>current.map(d=>{const r=data.result.find((v:{id:string})=>v.id===d.id);return r?{...d,category:r.category,duplicate:r.similar||d.duplicate,selected:r.similar?false:d.selected,ai:true}:d;}));setAiApplied(true);setAiBusy(false);setAiStatus('Suggested categories are ready. Check them before saving.');}};
  worker.current.onerror=()=>{setAiError('AI could not load on this device or network. You can still review and save every wish manually.');setAiBusy(false);worker.current?.terminate();worker.current=null;};
  worker.current.postMessage({items:list.map(d=>({id:d.id,title:d.title})),existing:wishes.map(w=>({title:w.title}))});
 }
 function cancelAI(){worker.current?.terminate();worker.current=null;setAiBusy(false);setAiStatus('');}
 function changeDraft(id:string,patch:Partial<Draft>){setDrafts(list=>list.map(d=>d.id===id?{...d,...patch}:d));setDraftError('');}
 async function saveDrafts(){const items=drafts.filter(d=>d.selected);if(!items.length){setDraftError('Select at least one wish to save.');return;}for(const d of items){const check=wishInput.safeParse(d);if(!check.success){setDraftError(check.error.issues[0].message);return;}}setSaving(true);try{const r=await request('/api/wishes',{method:'POST',body:JSON.stringify({items})});setWishes(r.wishes);announceChange();setError('');setReview(false);setDrafts([]);setRaw('');toast.success(`${items.length} ${items.length===1?'wish':'wishes'} saved for your tomorrows.`);}catch(e){setDraftError((e as Error).message);}finally{setSaving(false);}}
 async function update(w:Wish){const valid=wishInput.safeParse(w);if(!valid.success){setEditError(valid.error.issues[0].message);return;}setSaving(true);try{const r=await request('/api/wishes',{method:'PATCH',body:JSON.stringify(w)});setWishes(list=>list.map(v=>v.id===r.wish.id?r.wish:v));setEditing(null);announceChange();setEditError('');toast.success(w.status==='Done'?'Another dream made real.':'Wish saved.');}catch(e){setEditError((e as Error).message);toast.error((e as Error).message);await refresh();}finally{setSaving(false);}}
 async function remove(){if(!removing)return;setSaving(true);try{await request('/api/wishes',{method:'DELETE',body:JSON.stringify({id:removing.id,revision:removing.revision})});setWishes(list=>list.filter(w=>w.id!==removing.id));setRemoving(null);setEditing(null);announceChange();toast.success('Wish removed.');}catch(e){toast.error((e as Error).message);await refresh();}finally{setSaving(false);}}
 const filtered=wishes.filter(w=>(collection==='All'||collection==='Together'&&people.every(p=>likes(w.id,p))||likes(w.id,collection))&&(category==='All categories'||w.category===category)&&(status==='All wishes'||w.status===status)&&[w.title,w.notes,w.url,w.category].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==='Priority'?priorities.indexOf(b.priority)-priorities.indexOf(a.priority):sort==='Target date'?(a.dueDate||'9999').localeCompare(b.dueDate||'9999'):b.createdAt.localeCompare(a.createdAt));
 return <section className="wishes-section">
  <div className="section-top"><div><p className="eyebrow">WISHLIST · 願望</p><h2>For all our <em>tomorrows.</em></h2><p className="quiet">{wishes.filter(w=>w.status!=='Done').length} wishes ahead · {wishes.filter(w=>w.status==='Done').length} made real</p></div><Button variant="outline" onClick={()=>{setDrafts([makeDraft()]);setDraftError('');setAiError('');setAiApplied(false);setReview(true);}}><Plus/>Add a wish</Button></div>
  <div className="wish-capture"><div className="capture-heading"><Sparkles size={22}/><div><h3>Let’s put a little wish into words.</h3><p>Paste ideas or links. One wish per line or semicolon. English or Chinese is welcome.</p></div></div><Textarea id="quick-wishes" aria-label="Ideas for our wishlist" value={raw} maxLength={15000} onChange={e=>{setRaw(e.target.value);setDraftError('');}} rows={4} placeholder={'想一起去看極光\nTry a pottery class together\nA camera I found: https://…'}/><div className="capture-actions"><Button onClick={()=>prepare(true)} disabled={!raw.trim()||loading||!!error}><Sparkles size={17}/>Organise with AI</Button><Button variant="outline" onClick={()=>prepare()} disabled={!raw.trim()||loading||!!error}>Split & review<ArrowRight size={17}/></Button><span className="capture-note">You review every card before saving.</span></div><p className="model-note">AI suggests categories and similar wishes on your device. First use downloads a multilingual model; no API key needed. Use “Split & review” to skip the download.</p>{draftError&&!review&&<p className="field-error" role="alert">{draftError}</p>}</div>
  {error&&<div className="error-banner" role="alert">{error}<Button variant="outline" onClick={refresh}><RefreshCw/>Retry</Button></div>}
  <div className="collection-bar"><Choice label="Collecting for" value={collector} options={people} onChange={v=>{setCollector(v);try{localStorage.setItem('yc-collector',v);}catch{}}}/><div className="filter-row" role="group" aria-label="Wish collections">{['All',...people,'Together'].map(v=><Button key={v} variant="ghost" aria-pressed={collection===v} className={collection===v?'filter active':'filter'} onClick={()=>setCollection(v)}>{v==='Together'?'Both of us ❤':v}</Button>)}</div></div>{entryError&&<p className="field-error" role="alert">{entryError}</p>}<div className="wish-toolbar"><div className="search-field"><Search size={18}/><Input aria-label="Search wishes" placeholder="Find a wish…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Choice label="Category" value={category} options={['All categories',...categories]} onChange={setCategory}/><Choice label="Status" value={status} options={['All wishes',...statuses]} onChange={setStatus}/><Choice label="Sort wishes" value={sort} options={['Newest','Priority','Target date']} onChange={setSort}/></div>
  {loading&&!loaded?<p role="status" className="loading-note">Opening your wishes…</p>:filtered.length?<div className="wish-grid">{filtered.map(w=>{const Icon=icons[w.category];return <article className={'wish-card '+(w.status==='Done'?'wish-done':'')} key={w.id}><div className="wish-card-top"><span className={'category-icon '+w.category.toLowerCase()}><Icon size={20}/></span><span className="category-label">{w.category}</span><Button size="icon" variant="ghost" aria-label={'Edit '+w.title} onClick={()=>{setEditError('');setEditing({...w});}}><Pencil size={16}/></Button></div><h3>{w.title}</h3>{w.notes&&<p className="wish-note">{w.notes}</p>}<div className="wish-details"><span className={'priority '+(w.priority==='Top wish'?'top-wish':'')}>{w.priority==='Top wish'&&<Heart size={12}/>} {w.priority}</span>{w.budget!==null&&<span>{w.currency?`${w.currency} `:''}{w.budget.toLocaleString()} budget</span>}{w.dueDate&&<span>By {w.dueDate}</span>}</div>{w.url&&<a className="wish-source" href={w.url} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>{new URL(w.url).hostname}</a>}<div className="wish-interests"><Button variant="outline" disabled={interestBusy||!!entryError} aria-pressed={likes(w.id,collector)} onClick={()=>toggleInterest(w)}><Heart size={15} fill={likes(w.id,collector)?'currentColor':'none'}/>{likes(w.id,collector)?'Collected':'I would love this'}</Button><span className="small-meta">{people.filter(p=>likes(w.id,p)).join(' + ')||'Choose whose wishlist to keep it in'}</span></div>{entries.filter(e=>e.kind==='memory'&&e.data.wishId===w.id).map(e=>e.kind==='memory'&&<p key={e.id} className="wish-memory-link">Kept in Memories · {e.data.date}</p>)}<div className="wish-card-footer"><span className={'wish-status '+w.status.toLowerCase()}>{w.status}</span><Button variant="ghost" disabled={saving} onClick={()=>w.status==='Done'?update({...w,status:'Dreaming'}):setCompleting(w)}>{w.status==='Done'?'Dream again':'We did it · keep memory'}<Check size={15}/></Button></div></article>;})}</div>:<Empty className="wish-empty"><EmptyHeader><EmptyMedia variant="icon"><Sparkles/></EmptyMedia><EmptyTitle>{wishes.length?'No wishes match this view.':'A small wish is a lovely place to start.'}</EmptyTitle><EmptyDescription>{wishes.length?'Change your filters to find the others.':'A meal, a journey, a book, or an ordinary Sunday together. Write what you would love to do.'}</EmptyDescription></EmptyHeader><EmptyContent><Button variant="outline" onClick={()=>{if(wishes.length){setQuery('');setCategory('All categories');setStatus('All wishes');setCollection('All');}else document.getElementById('quick-wishes')?.focus();}}>{wishes.length?'Show all wishes':'Write our first wish'}<ArrowRight size={16}/></Button></EmptyContent></Empty>}
  <Dialog open={review} onOpenChange={v=>{if(!saving){if(!v)cancelAI();setReview(v);}}}><DialogContent className="wish-review-dialog"><DialogTitle>A little room for every wish</DialogTitle><DialogDescription>{aiApplied?'AI has suggested categories and similar wishes. Edit anything, and select the cards you want to keep.':'The text is split at line breaks and semicolons. Edit each card, or use AI to suggest categories and find similar wishes.'}</DialogDescription><div className="review-ai-bar"><Button variant="outline" disabled={aiBusy||saving||!drafts.length} onClick={()=>organise()}><Sparkles size={16}/>{aiApplied?'Organise again':'Suggest categories with AI'}</Button><span className="small-meta">First download may take a few minutes.</span></div>{aiBusy&&<div className="ai-progress" role="status"><LoaderCircle className="spin" size={18}/><span>{aiStatus}</span><Button size="sm" variant="ghost" onClick={cancelAI}>Cancel</Button></div>}{aiError&&<p className="field-error" role="alert">{aiError}</p>}
   <div className="draft-list">{drafts.map((d,i)=><div key={d.id} className={'draft-card '+(d.selected?'':'draft-unselected')}><div className="draft-head"><Checkbox id={'keep-'+d.id} checked={d.selected} disabled={saving||aiBusy} onCheckedChange={v=>changeDraft(d.id,{selected:!!v})}/><label htmlFor={'keep-'+d.id}>Keep wish {i+1}</label><Button size="icon" variant="ghost" aria-label={'Discard draft '+(i+1)} disabled={saving||aiBusy} onClick={()=>setDrafts(list=>list.filter(v=>v.id!==d.id))}><X size={16}/></Button></div>{d.duplicate&&<p className="duplicate-note">Similar to “{d.duplicate}”. Keep both only if you want two separate wishes.</p>}<WishFields value={d} prefix={d.id} disabled={saving||aiBusy} onChange={v=>changeDraft(d.id,v)}/></div>)}</div>{draftError&&<p className="field-error" role="alert">{draftError}</p>}<div className="review-bottom"><span>{drafts.filter(d=>d.selected).length} selected</span><Button disabled={saving||aiBusy||!drafts.some(d=>d.selected)} onClick={saveDrafts}>{saving?'Saving…':'Save selected wishes'}<Heart size={16}/></Button></div>
  </DialogContent></Dialog>
  <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!saving)setEditing(null);}}><DialogContent className="wish-edit-dialog"><DialogTitle>Give this wish a little shape</DialogTitle><DialogDescription>Keep the idea, link, and details together.</DialogDescription>{editing&&<WishFields value={editing} prefix="edit" disabled={saving} onChange={v=>setEditing({...editing,...v})}/>}{editError&&<p role="alert" className="field-error">{editError}</p>}<div className="dialog-actions"><Button disabled={saving} onClick={()=>editing&&update(editing)}>{saving?'Saving…':'Save wish'}</Button><Button variant="ghost" disabled={saving} onClick={()=>setRemoving(editing)}><Trash2 size={17}/>Remove</Button></div></DialogContent></Dialog>
  {completing&&<MemoryComposer photos={photos} wish={completing} onClose={()=>setCompleting(null)} onSaved={()=>{refresh();onMemorySaved();}}/>}
  <Confirm open={!!removing} title="Remove this wish?" description="This removes the wish and its notes from your shared list." busy={saving} onClose={()=>setRemoving(null)} onConfirm={remove}/>
 </section>;
}
function WishFields({value:v,onChange,prefix,disabled}:{value:WishInput;onChange:(v:Partial<WishInput>)=>void;prefix:string;disabled:boolean}){return <fieldset disabled={disabled} className="wish-fields"><Field id={prefix+'-title'} label="The wish"><Input id={prefix+'-title'} value={v.title} maxLength={160} onChange={e=>onChange({title:e.target.value})} placeholder="Something we would love…"/></Field><div className="form-triple"><Choice label="Category" value={v.category} options={categories} disabled={disabled} onChange={x=>onChange({category:x as WishInput['category']})}/><Choice label="Priority" value={v.priority} options={priorities} disabled={disabled} onChange={x=>onChange({priority:x as WishInput['priority']})}/><Choice label="Status" value={v.status} options={statuses} disabled={disabled} onChange={x=>onChange({status:x as WishInput['status']})}/></div><Field id={prefix+'-link'} label="Link (optional)"><Input type="url" id={prefix+'-link'} value={v.url} maxLength={2048} placeholder="https://…" onChange={e=>onChange({url:e.target.value})}/></Field><details className="wish-more"><summary>Notes, budget & target date</summary><Field label="Notes" id={prefix+'-notes'}><Textarea id={prefix+'-notes'} rows={2} value={v.notes} maxLength={3000} onChange={e=>onChange({notes:e.target.value})}/></Field><div className="form-triple"><Field label="Budget (optional)" id={prefix+'-budget'}><Input id={prefix+'-budget'} type="number" inputMode="decimal" min="0" max="100000000" step="0.01" value={v.budget??''} onChange={e=>onChange({budget:e.target.value===''?null:Number(e.target.value)})}/></Field><Choice label="Currency" value={v.currency||'unspecified'} options={[{value:'unspecified',label:'Not set'},...['CAD','USD','CNY','EUR','GBP'].map(value=>({value,label:value}))]} disabled={disabled} onChange={x=>onChange({currency:(x==='unspecified'?'':x) as WishInput['currency']})}/><Field label="Target date" id={prefix+'-date'}><Input id={prefix+'-date'} type="date" value={v.dueDate} onChange={e=>onChange({dueDate:e.target.value})}/></Field></div></details></fieldset>;}
