"use client";
import {Photo,Wish} from './models';
import {Entry,Asset} from './v5-models';
import {poemSets} from './poems';
import {request} from './wish-drafts';
import {downloadBlob} from './v5-client';
export function photoYear(p:Photo,entries:Entry[]){const linked=entries.filter(e=>e.kind==='memory'&&e.data.photoIds.includes(p.id)).map(e=>e.kind==='memory'?e.data.date:'').sort()[0];return (p.takenAt||linked||p.createdAt).slice(0,4);}
export function wishDate(w:Wish,entries:Entry[]){const date=entries.filter(e=>e.kind==='memory'&&e.data.wishId===w.id).map(e=>e.kind==='memory'?e.data.date:'').sort().at(-1);return date||w.updatedAt.slice(0,10);}
async function media(url:string,signal?:AbortSignal){const r=await fetch(url,{credentials:'same-origin',signal});if(!r.ok)throw new Error('A media file could not be downloaded. The export was stopped so it does not silently omit anything.');return r;}
function dataUrl(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=()=>reject(new Error('Could not read a photograph for the PDF.'));reader.readAsDataURL(blob);});}
export async function exportYearbook({year,photos,wishes,entries,setId,progress,signal}:{year:string;photos:Photo[];wishes:Wish[];entries:Entry[];setId:string;progress:(s:string)=>void;signal:AbortSignal}){
 const [{jsPDF},{toJpeg}]=await Promise.all([import('jspdf'),import('html-to-image')]);const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});pdf.setProperties({title:`Yuliya & Chih-hsing — ${year}`,author:'Yuliya & Chih-hsing',subject:'Our photographs, poetry, and wishes made real'});const poems=(poemSets.find(s=>s.id===setId)||poemSets[0]).poems;const root=document.createElement('div');root.style.cssText='position:fixed;left:-12000px;top:0;width:794px;pointer-events:none;z-index:-10;';document.body.appendChild(root);const pages:HTMLDivElement[]=[];let current!:HTMLDivElement;
 function el<K extends keyof HTMLElementTagNameMap>(tag:K,text='',style=''){const e=document.createElement(tag);e.textContent=text;e.style.cssText=style;return e;}
 function page(kicker:string,title:string){const page=el('div','','width:794px;height:1123px;padding:52px 54px 44px;background:#fffaf8;color:#492a38;font-family:Arial,"Noto Serif TC","Microsoft JhengHei",sans-serif;position:relative;box-sizing:border-box;');const header=el('div',`Y❤C  /  ${year}  /  ${kicker}`,'font-size:13px;letter-spacing:2px;border-bottom:1px solid #dcbecb;padding-bottom:12px;margin-bottom:20px;');page.appendChild(header);const body=el('div','','height:927px;overflow:hidden;display:flow-root;');body.appendChild(el('h2',title,'font-family:Georgia,"Noto Serif TC",serif;font-size:30px;line-height:1.3;margin:0 0 22px;overflow-wrap:anywhere;'));page.appendChild(body);const footer=el('div',`Yuliya × Chih-hsing                                      ${pages.length+1}`,'position:absolute;bottom:24px;left:54px;right:54px;font-size:12px;color:#946f80;border-top:1px solid #e5ced8;padding-top:10px;');page.appendChild(footer);pages.push(page);root.appendChild(page);current=body;return body;}
 function append(block:Node,title:string){current.appendChild(block);if(current.scrollHeight>current.clientHeight){current.removeChild(block);page('CONTINUED',title);current.appendChild(block);}}
 function paragraphs(text:string,title:string,label=''){if(!text)return;let rest=text;let first=true;while(rest){let length=Math.min(rest.length,400);if(length<rest.length){const space=rest.lastIndexOf(' ',length);if(space>250)length=space;}const part=rest.slice(0,length);rest=rest.slice(length).trimStart();append(el('p',(first&&label?label+'\n':'')+part,'font-size:18px;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere;margin:0 0 18px;'),title);first=false;}}
 try{page('OUR YEAR',year);current.appendChild(el('h1','Yuliya ♥ Chih-hsing','font-family:Georgia,serif;font-size:57px;line-height:1.18;font-weight:normal;margin:80px 0 32px;'));current.appendChild(el('p','A year of choosing each other.','font-family:Georgia,serif;font-size:28px;line-height:1.6;'));current.appendChild(el('p',poems[5].lines.join('，')+'。','font-family:"KaiTi","Microsoft JhengHei",serif;font-size:27px;line-height:1.7;margin-top:70px;'));current.appendChild(el('p',poems[5].source,'font-size:16px;color:#946f80;margin-top:14px;'));current.appendChild(el('p',`${photos.length} photographs · ${wishes.length} wishes made real`,'font-size:17px;margin-top:70px;'));
 for(const [i,p]of photos.entries()){if(signal.aborted)throw new DOMException('Cancelled','AbortError');progress(`Preparing photograph ${i+1} of ${photos.length}…`);page('A MOMENT TO KEEP',p.title);append(el('p',p.takenAt||p.createdAt.slice(0,10),'font-size:15px;color:#946f80;margin:0 0 16px;'),p.title);const img=document.createElement('img');img.src=await dataUrl(await (await media('/api/media/'+p.id,signal)).blob());img.style.cssText='display:block;width:100%;height:480px;object-fit:contain;background:#f4e9ed;margin:0 0 22px;';await img.decode();append(img,p.title);const poem=poems[p.slot??i%6];append(el('p',poem.lines.join('，')+'。\n'+poem.source,'font-family:"KaiTi","Microsoft JhengHei",serif;font-size:21px;line-height:1.7;color:#754258;white-space:pre-line;margin:0 0 20px;'),p.title);paragraphs(p.note,p.title);for(const e of entries)if(e.kind==='perspective'&&e.data.photoId===p.id)paragraphs(e.data.text,p.title,e.data.person+' remembers');}
 if(wishes.length){page('DREAMS MADE REAL','The things we did together.');for(const w of wishes){append(el('h3',w.title,'font-family:Georgia,"Microsoft JhengHei",serif;font-size:25px;line-height:1.4;margin:26px 0 10px;'), 'Dreams made real');append(el('p',wishDate(w,entries),'font-size:15px;color:#946f80;margin:0 0 10px;'),'Dreams made real');paragraphs(w.notes,'Dreams made real');for(const e of entries)if(e.kind==='memory'&&e.data.wishId===w.id)paragraphs(e.data.notes,'Dreams made real','How it felt');}}
 await document.fonts.ready;for(const [i,p]of pages.entries()){if(signal.aborted)throw new DOMException('Cancelled','AbortError');progress(`Making PDF page ${i+1} of ${pages.length}…`);const jpeg=await toJpeg(p,{quality:.94,pixelRatio:1.6,width:794,height:1123,backgroundColor:'#fffaf8',skipFonts:true});if(i)pdf.addPage();pdf.addImage(jpeg,'JPEG',0,0,210,297,undefined,'FAST');}if(signal.aborted)throw new DOMException('Cancelled','AbortError');pdf.save(`YC_${year}_Yearbook.pdf`);
 }finally{root.remove();}
}
export async function exportBackup(progress:(s:string)=>void,signal:AbortSignal){const {Zip,ZipPassThrough,strToU8}=await import('fflate');const manifest=await request('/api/backup',{method:'POST',body:JSON.stringify({confirmFullArchive:true})});const token=manifest.exportToken;delete manifest.exportToken;const files:{path:string;url:string;size:number}[]=[];const safe=(name:string)=>name.replace(/[^\p{L}\p{N}._-]/gu,'_').slice(0,150);for(const p of manifest.photos as Photo[])files.push({path:`media/${p.id}-${safe(p.filename)}`,url:'/api/media/'+p.id,size:p.size});for(const a of manifest.assets as Asset[])files.push({path:`attachments/${a.id}-${safe(a.filename)}`,url:`/api/assets/${a.id}?export=${encodeURIComponent(token)}`,size:a.size});manifest.files=files.map(({path,size})=>({path,size}));try{manifest.displayPreferences=JSON.parse(localStorage.getItem('yc-display-preferences')||'null');}catch{manifest.displayPreferences=null;}const chunks:Uint8Array[]=[];let resolveZip:(v:Blob)=>void,rejectZip:(e:unknown)=>void;const done=new Promise<Blob>((resolve,reject)=>{resolveZip=resolve;rejectZip=reject;});const zip=new Zip((err,data,final)=>{if(err){rejectZip(err);return;}if(data)chunks.push(data);if(final)resolveZip(new Blob(chunks as BlobPart[],{type:'application/zip'}));});function addText(name:string,text:string){const f=new ZipPassThrough(name);zip.add(f);f.push(strToU8(text),true);}try{addText('manifest.json',JSON.stringify(manifest,null,2));addText('READ_ME.txt','Yuliya × Chih-hsing — complete archive backup, format v5\n\nThis ZIP contains private photos, HEIC originals, audio, video, wishes, plans, perspectives, nicknames, quiz progress and sealed letters. Keep it somewhere private.\nmanifest.json preserves record IDs and metadata. Files are named with their record IDs. This is a portable export, not a one-click restore package.\nNo authentication tokens or server credentials are included.\n');for(const [i,f]of files.entries()){if(signal.aborted)throw new DOMException('Cancelled','AbortError');progress(`Backing up ${i+1}/${files.length}: ${f.path.split('/').at(-1)}`);const response=await media(f.url,signal),item=new ZipPassThrough(f.path);zip.add(item);const reader=response.body?.getReader();if(!reader)throw new Error('A download stream was unavailable.');let received=0;while(true){const {done,value}=await reader.read();if(done)break;received+=value.byteLength;item.push(value);}if(received!==f.size)throw new Error('A media file was incomplete. Please retry the backup.');item.push(new Uint8Array(),true);}zip.end();const blob=await done;if(signal.aborted)throw new DOMException('Cancelled','AbortError');downloadBlob(blob,`YC_Backup_${new Date().toISOString().slice(0,10)}.zip`);}catch(e){zip.terminate();chunks.length=0;throw e;}}
