"use client";
import {useCallback,useEffect,useState} from 'react';
import {request} from './wish-drafts';
import {Entry,EntryInput,Asset} from './v5-models';
export function announceChange(){window.dispatchEvent(new Event('yc-archive-change'));}
export function useEntries(active=true){const [entries,setEntries]=useState<Entry[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[loaded,setLoaded]=useState(false);const refresh=useCallback(async()=>{setLoading(true);try{const r=await request('/api/entries');setEntries(r.entries);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);setLoaded(true);}},[]);useEffect(()=>{if(!active)return;refresh();const update=()=>{if(document.visibilityState==='visible')refresh();};window.addEventListener('yc-archive-change',update);window.addEventListener('focus',update);return()=>{window.removeEventListener('yc-archive-change',update);window.removeEventListener('focus',update);};},[active,refresh]);return {entries,error,loading,loaded,refresh};}
export async function saveEntry(v:EntryInput,existing?:Entry,extra?:Record<string,unknown>){const r=await request('/api/entries',{method:existing?'PATCH':'POST',body:JSON.stringify({...v,...(existing?{revision:existing.revision}:{}),...extra})});announceChange();return r.entry as Entry;}
export async function deleteEntry(v:Entry){await request('/api/entries',{method:'DELETE',body:JSON.stringify({id:v.id,revision:v.revision})});announceChange();}
export function useAssets(parentId:string){const [assets,setAssets]=useState<Asset[]>([]),[error,setError]=useState('');const refresh=useCallback(async()=>{try{const r=await request('/api/assets?parentId='+encodeURIComponent(parentId));setAssets(r.assets);setError('');}catch(e){setError((e as Error).message);}},[parentId]);useEffect(()=>{refresh();},[refresh]);return {assets,error,refresh};}
export async function uploadAsset(file:Blob,filename:string,parentType:Asset['parentType'],parentId:string,purpose:Asset['purpose'],person='Yuliya'){const r=await request('/api/assets',{method:'POST',body:file,headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(filename),'X-Parent-Type':parentType,'X-Parent-Id':parentId,'X-Asset-Purpose':purpose,'X-Person':person}});announceChange();return r.asset as Asset;}
export const photoAccept='image/jpeg,image/png,image/webp,image/gif,image/heic,image/heif,.heic,.heif';
export function isHeic(file:File){return /\.(heic|heif)$/i.test(file.name)||['image/heic','image/heif'].includes(file.type);}
export async function preparePhoto(file:File):Promise<File>{if(file.size>24*1024*1024)throw new Error('Choose a photo up to 24 MB (12 MB for JPG, PNG, WebP or GIF).');if(!isHeic(file)){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw new Error('Choose JPG, PNG, WebP, GIF, or HEIC.');if(file.size>12*1024*1024)throw new Error('This photograph is over 12 MB.');return file;}let blob:Blob;try{const {default:convert}=await import('heic2any');const result=await convert({blob:file,toType:'image/jpeg',quality:.9});blob=Array.isArray(result)?result[0]:result;}catch{throw new Error('This HEIC variant could not be converted. Export it as JPEG in Photos, then try again.');}if(blob.size>12*1024*1024)throw new Error('The converted photo exceeds 12 MB. Export a smaller JPEG in Photos.');return new File([blob],file.name.replace(/\.(heic|heif)$/i,'')+'.jpg',{type:'image/jpeg'});}
export async function uploadPhoto(file:File){const prepared=await preparePhoto(file);const r=await request('/api/photos',{method:'POST',body:prepared,headers:{'Content-Type':prepared.type,'X-File-Name':encodeURIComponent(prepared.name)}});if(isHeic(file)){try{await uploadAsset(new Blob([file],{type:/heif$/i.test(file.name)?'image/heif':'image/heic'}),file.name,'photo',r.photo.id,'original');}catch(e){throw new Error('The JPEG was saved, but the HEIC original was not. Retry this upload to finish saving the original. '+(e as Error).message);}}announceChange();return r;}
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
