import {db,HttpError,bucket,identity} from './server';
import {Entry,EntryInput,entryInput} from './v5-models';
export const entrySelect='SELECT id,kind,data,created_at AS createdAt,updated_at AS updatedAt,revision FROM entries';
export const assetSelect='SELECT id,parent_type AS parentType,parent_id AS parentId,purpose,person,filename,mime,size,created_at AS createdAt FROM assets';
export function decodeEntry(row:any,redact=true):Entry{const entry={...row,data:typeof row.data==='string'?JSON.parse(row.data):row.data} as Entry;if(entry.kind==='capsule'){entry.locked=entry.data.stage==='sealed'&&new Date(entry.data.unlockAt).getTime()>Date.now();if(redact&&entry.locked)entry.data={...entry.data,body:''};}return entry;}
export async function entryById(id:string,redact=true){const r=await db().prepare(entrySelect+' WHERE id=?').bind(id).first();return r?decodeEntry(r,redact):null;}
export async function allEntries(redact=true){return(await db().prepare(entrySelect+' ORDER BY created_at DESC').all()).results.map(r=>decodeEntry(r,redact));}
export function entryKey(v:EntryInput){return v.kind==='perspective'?`perspective:${v.data.photoId}:${v.data.person}`:v.kind==='interest'?`interest:${v.data.wishId}:${v.data.person}`:null;}
export async function validateReferences(v:EntryInput){
 const photoIds=v.kind==='memory'?v.data.photoIds:v.kind==='perspective'?[v.data.photoId]:[];
 for(const id of photoIds)if(!await db().prepare("SELECT id FROM photos WHERE id=? AND kind='photo'").bind(id).first())throw new HttpError(400,'A selected photograph no longer exists. Please refresh.');
 const wishId=v.kind==='interest'?v.data.wishId:v.kind==='memory'?v.data.wishId:null;
 if(wishId&&!await db().prepare('SELECT id FROM wishes WHERE id=?').bind(wishId).first())throw new HttpError(400,'The selected wish no longer exists.');
}
export async function assetParent(parentType:string,parentId:string,writing=false){
 if(parentType==='capsule'){const e=await entryById(parentId);if(!e||e.kind!=='capsule')throw new HttpError(404,'Letter not found.');if(writing&&e.data.stage==='sealed')throw new HttpError(409,'This letter is sealed. Its attachments can no longer change.');if(!writing&&e.locked)throw new HttpError(423,'This letter opens on '+new Date(e.data.unlockAt).toLocaleDateString('en-CA')+'.');return;}
 if(parentType==='photo'&&!await db().prepare("SELECT id FROM photos WHERE id=? AND kind='photo'").bind(parentId).first())throw new HttpError(404,'Photograph not found.');
 if(parentType==='poem'&&!/^[0-5]$/.test(parentId))throw new HttpError(400,'Choose one of the six poems.');
 if(!['photo','capsule','poem'].includes(parentType))throw new HttpError(400,'Choose a photograph, poem, or letter.');
}
export async function validExportTicket(req:Request){const token=new URL(req.url).searchParams.get('export');if(!token)return false;return !!await db().prepare('SELECT id FROM export_tickets WHERE id=? AND user_id=? AND expires_at>?').bind(token,identity(req),new Date().toISOString()).first();}
export function mediaSignature(b:Uint8Array,mime:string){const a=(i:number,n:number)=>String.fromCharCode(...b.slice(i,i+n));if(mime==='image/jpeg')return b[0]===255&&b[1]===216&&b[2]===255;if(mime==='image/png')return b[0]===137&&a(1,3)==='PNG';if(mime==='image/gif')return ['GIF87a','GIF89a'].includes(a(0,6));if(mime==='image/webp')return a(0,4)==='RIFF'&&a(8,4)==='WEBP';if(['image/heic','image/heif'].includes(mime))return a(4,4)==='ftyp'&&/(heic|heix|hevc|hevx|mif1|msf1)/.test(a(8,32));if(mime==='audio/webm')return b[0]===26&&b[1]===69&&b[2]===223&&b[3]===163;if(mime==='audio/ogg')return a(0,4)==='OggS';if(mime==='audio/wav'||mime==='audio/x-wav')return a(0,4)==='RIFF'&&a(8,4)==='WAVE';if(mime==='audio/mpeg')return a(0,3)==='ID3'||(b[0]===255&&(b[1]&224)===224);if(mime==='audio/mp4'||mime==='audio/x-m4a')return a(4,4)==='ftyp';return false;}
export async function serveStoredMedia(req:Request,media:{object_key:string;mime:string;size:number}){const header=req.headers.get('range');let range:{offset:number;length:number}|undefined;if(header){const m=/^bytes=(\d*)-(\d*)$/.exec(header);let start=NaN,end=NaN;if(m&&(m[1]||m[2])){if(m[1]){start=Number(m[1]);end=m[2]?Math.min(Number(m[2]),media.size-1):media.size-1;}else{start=Math.max(0,media.size-Number(m[2]));end=media.size-1;}}if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||start>=media.size||end<start)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${media.size}`}});range={offset:start,length:end-start+1};}const o=await bucket().get(media.object_key,range?{range}:undefined);if(!o)throw new HttpError(404,'Attachment not found.');const h=new Headers({'Content-Type':media.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes','Content-Length':String(range?.length??o.size)});if(range)h.set('Content-Range',`bytes ${range.offset}-${range.offset+range.length-1}/${o.size}`);return new Response(o.body,{status:range?206:200,headers:h});}
