import {Miniflare} from 'miniflare';
import {build} from 'esbuild';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'yc-check-'));
const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-05-15',d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false});
let checks=0;
async function module(path,name){const out=join(dir,name+'.mjs');await build({entryPoints:[path],outfile:out,bundle:true,platform:'node',format:'esm',logLevel:'silent',plugins:[{name:'isolated-test-bindings',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'cloudflare:workers',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.__giftTestEnv;',loader:'js'}));}}]});return import(pathToFileURL(out));}
function req(path,method='GET',data,extra={}){return new Request('https://gift.test'+path,{method,headers:{'oai-authenticated-user-id':'test-viewer','oai-authenticated-user-email':'bounniecrisis@gmail.com','content-type':'application/json',...extra},...(data!==undefined?{body:typeof data==='string'||data instanceof Uint8Array?data:JSON.stringify(data)}:{})});}
async function result(r,expected=200){assert.equal(r.status,expected,await r.clone().text());checks++;return r.json();}
try{
 const DB=await mf.getD1Database('DB'),BUCKET=await mf.getR2Bucket('BUCKET');globalThis.__giftTestEnv={DB,BUCKET,EDITOR_EMAILS:'bounniecrisis@gmail.com,changyue960915@gmail.com'};
 for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint').filter(s=>s.trim()))await DB.prepare(sql).run();
 const photos=await module('app/api/photos/route.ts','photos'),photo=await module('app/api/photos/[id]/route.ts','photo'),media=await module('app/api/media/[id]/route.ts','media'),wishes=await module('app/api/wishes/route.ts','wishes'),journey=await module('app/api/journey/route.ts','journey'),drafts=await module('lib/wish-drafts.ts','drafts');
 await result(await photos.GET(new Request('https://gift.test/api/photos')),401);
 await result(await wishes.POST(req('/api/wishes','POST',{items:[]},{origin:'https://other.test'})),403);
 const parsed=drafts.splitDrafts('想一起看極光\nA camera CAD 250; https://example.com/gift',[]);assert.equal(parsed.length,3);assert.equal(parsed[1].budget,250);assert.equal(parsed[1].currency,'CAD');assert.equal(parsed[2].url,'https://example.com/gift');checks+=4;
 assert.equal(drafts.splitDrafts('Pottery class',[{title:'pottery class',url:''}])[0].selected,false);checks++;
 const item={...drafts.makeDraft('Learn pottery together'),category:'Learning'};
 await result(await wishes.POST(req('/api/wishes','POST',{items:[item]})),201);
 await result(await wishes.POST(req('/api/wishes','POST',{items:[item]})),201);
 let ws=(await result(await wishes.GET(req('/api/wishes')))).wishes;assert.equal(ws.length,1);checks++;
 await result(await wishes.POST(req('/api/wishes','POST',{items:[{...item,id:crypto.randomUUID(),url:'javascript:alert(1)'}]})),400);
 const updated=(await result(await wishes.PATCH(req('/api/wishes','PATCH',{...ws[0],status:'Done'})))).wish;assert.equal(updated.status,'Done');checks++;
 await result(await wishes.PATCH(req('/api/wishes','PATCH',{...ws[0],status:'Planning'})),409);
 const png=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64'));
 await result(await photos.POST(req('/api/photos','POST',new Uint8Array([1,2,3]),{'content-type':'image/png'})),415);
 const saved=(await result(await photos.POST(req('/api/photos','POST',png,{'content-type':'image/png','x-file-name':encodeURIComponent('First memory.png')})),201)).photo;
 assert.equal((await result(await photos.POST(req('/api/photos','POST',png,{'content-type':'image/png'})))).duplicate,true);checks++;
 const context={params:Promise.resolve({id:saved.id})};
 const paired=(await result(await photo.PATCH(req('/api/photos/'+saved.id,'PATCH',{...saved,title:'First meeting',slot:0}),context))).photo;assert.equal(paired.slot,0);checks++;
 await result(await photo.PATCH(req('/api/photos/'+saved.id,'PATCH',{...saved,title:'Old edit',slot:1}),context),409);
 const secondBytes=new Uint8Array([...png,0]);const second=(await result(await photos.POST(req('/api/photos','POST',secondBytes,{'content-type':'image/png'})),201)).photo;
 await result(await photo.PATCH(req('/api/photos/'+second.id,'PATCH',{...second,slot:0}),{params:Promise.resolve({id:second.id})}));
 const rows=(await result(await photos.GET(req('/api/photos')))).photos;assert.equal(rows.find(p=>p.id===saved.id).slot,null);assert.equal(rows.find(p=>p.id===second.id).slot,0);checks+=2;
 const bytes=await media.GET(req('/api/media/'+saved.id,'GET',undefined,{range:'bytes=0-3'}),context);assert.equal(bytes.status,206);assert.equal((await bytes.arrayBuffer()).byteLength,4);checks+=2;
 await result(await journey.POST(req('/api/journey','POST',{index:3,answer:'hospital'})),400);
 const answers=['Vistopia','2026-5-21','陳丹青','hospital','知足常越','lifetime'];for(let i=0;i<6;i++){const r=await result(await journey.POST(req('/api/journey','POST',{index:i,answer:answers[i]})));assert.equal(r.correct,true);assert.equal(r.unlocked,i+1);checks+=2;}
 assert.equal((await result(await journey.GET(req('/api/journey')))).unlocked,6);checks++;

 const entries=await module('app/api/entries/route.ts','entries'),assets=await module('app/api/assets/route.ts','assets'),asset=await module('app/api/assets/[id]/route.ts','asset'),backup=await module('app/api/backup/route.ts','backup'),planner=await module('lib/life-plan.ts','planner');
 await result(await entries.GET(new Request('https://gift.test/api/entries')),401);
 const nicknameA={id:crypto.randomUUID(),kind:'nickname',data:{name:'Test nickname A',person:'Yuliya',since:'2026-09-10',origin:'A test origin, not real personal history.',funnyMoment:'測試趣事\nSecond line 🙂'}};
 const nicknameB={...nicknameA,id:crypto.randomUUID(),data:{...nicknameA.data,name:'Test nickname B',person:'Chih-hsing',since:''}};
 const savedNicknameA=(await result(await entries.POST(req('/api/entries','POST',nicknameA)),201)).entry;
 const savedNicknameB=(await result(await entries.POST(req('/api/entries','POST',nicknameB)),201)).entry;
 await result(await entries.POST(req('/api/entries','POST',{...nicknameA,id:crypto.randomUUID(),data:{...nicknameA.data,name:'   '}})),400);
 await result(await entries.POST(req('/api/entries','POST',{...nicknameA,id:crypto.randomUUID(),data:{...nicknameA.data,since:'2026-02-30'}})),400);
 const editedNickname=(await result(await entries.PATCH(req('/api/entries','PATCH',{...savedNicknameA,data:{...savedNicknameA.data,origin:'The origin, amended.'}})))).entry;
 await result(await entries.PATCH(req('/api/entries','PATCH',{...savedNicknameA,data:{...savedNicknameA.data,origin:'Stale overwrite'}})),409);
 const nicknameList=(await result(await entries.GET(req('/api/entries')))).entries;
 assert.equal(nicknameList.find(e=>e.id===savedNicknameB.id).data.origin,nicknameB.data.origin);assert.equal(nicknameList.find(e=>e.id===savedNicknameA.id).data.funnyMoment,nicknameA.data.funnyMoment);checks+=2;
 const memory={id:crypto.randomUUID(),kind:'memory',data:{title:'A wish made real',date:'2026-09-10',notes:'Two viewpoints, one lovely day.',photoIds:[saved.id],wishId:item.id,place:'A place we chose',lat:45.4,lng:-75.7}};
 const completion={...memory,completeWish:true,wishRevision:updated.revision};
 let memorySaved=(await result(await entries.POST(req('/api/entries','POST',completion)),201)).entry;
 assert.equal(memorySaved.data.wishId,item.id);checks++;
 assert.equal((await result(await entries.POST(req('/api/entries','POST',completion)))).duplicate,true);checks++;
 assert.equal((await result(await wishes.GET(req('/api/wishes')))).wishes[0].revision,updated.revision+1);checks++;
 await result(await entries.POST(req('/api/entries','POST',{...memory,id:crypto.randomUUID(),data:{...memory.data,date:'2026-02-30'}})),400);
 await result(await entries.POST(req('/api/entries','POST',{...memory,id:crypto.randomUUID(),data:{...memory.data,photoIds:[crypto.randomUUID()]}})),400);
 await result(await entries.POST(req('/api/entries','POST',{...memory,id:crypto.randomUUID(),data:{...memory.data,lat:null}})),400);
 const memoriesBefore=(await result(await entries.GET(req('/api/entries')))).entries.length;
 await result(await entries.POST(req('/api/entries','POST',{...completion,id:crypto.randomUUID()})),409);
 assert.equal((await result(await entries.GET(req('/api/entries')))).entries.length,memoriesBefore);checks++;
 const perspectiveA=(await result(await entries.POST(req('/api/entries','POST',{id:crypto.randomUUID(),kind:'perspective',data:{photoId:saved.id,person:'Yuliya',text:'I remember the light.'}})),201)).entry;
 const perspectiveB=(await result(await entries.POST(req('/api/entries','POST',{id:crypto.randomUUID(),kind:'perspective',data:{photoId:saved.id,person:'Chih-hsing',text:'I remember your smile.'}})),201)).entry;
 await result(await entries.PATCH(req('/api/entries','PATCH',{...perspectiveA,data:{...perspectiveA.data,text:'A little more light.'}})));
 await result(await entries.PATCH(req('/api/entries','PATCH',{...perspectiveA,data:{...perspectiveA.data,text:'stale'}})),409);
 assert.equal((await result(await entries.GET(req('/api/entries')))).entries.find(e=>e.id===perspectiveB.id).data.text,'I remember your smile.');checks++;
 await result(await entries.POST(req('/api/entries','POST',{...perspectiveA,id:crypto.randomUUID()})),409);
 for(const person of ['Yuliya','Chih-hsing'])await result(await entries.POST(req('/api/entries','POST',{id:crypto.randomUUID(),kind:'interest',data:{wishId:item.id,person,selected:true}})),201);
 let interests=(await result(await entries.GET(req('/api/entries')))).entries.filter(e=>e.kind==='interest');assert.equal(interests.filter(e=>e.data.selected).length,2);checks++;
 await result(await entries.PATCH(req('/api/entries','PATCH',{...interests[0],data:{...interests[0].data,selected:false}})));
 interests=(await result(await entries.GET(req('/api/entries')))).entries.filter(e=>e.kind==='interest');assert.equal(interests.filter(e=>e.data.selected).length,1);checks++;
 const audioBytes=new Uint8Array([26,69,223,163,0,0,0,0,4,5,6]);
 const voice=(await result(await assets.POST(req('/api/assets','POST',audioBytes,{'content-type':'audio/webm','x-parent-type':'photo','x-parent-id':saved.id,'x-asset-purpose':'voice','x-person':'Yuliya','x-file-name':'voice.webm'})),201)).asset;
 const voiceCtx={params:Promise.resolve({id:voice.id})};const voiceResponse=await asset.GET(req('/api/assets/'+voice.id),voiceCtx);assert.deepEqual(new Uint8Array(await voiceResponse.arrayBuffer()),audioBytes);checks++;
 const invalidRange=await asset.GET(req('/api/assets/'+voice.id,'GET',undefined,{range:'bytes=100-101'}),voiceCtx);assert.equal(invalidRange.status,416);checks++;
 await result(await assets.POST(req('/api/assets','POST',png,{'content-type':'image/png','x-parent-type':'photo','x-parent-id':saved.id,'x-asset-purpose':'voice'})),415);
 const heic=new Uint8Array([0,0,0,24,...Buffer.from('ftypheic'),0,0,0,0,...Buffer.from('mif1heic')]);
 const original=(await result(await assets.POST(req('/api/assets','POST',heic,{'content-type':'image/heic','x-parent-type':'photo','x-parent-id':saved.id,'x-asset-purpose':'original','x-file-name':'original.heic'})),201)).asset;
 assert.equal(original.mime,'image/heic');checks++;
 const capsule={id:crypto.randomUUID(),kind:'capsule',data:{title:'For our day',body:'These words must stay sealed.',person:'Chih-hsing',occasion:'Anniversary',unlockAt:'2099-09-10T12:00:00.000Z',stage:'draft'}};
 const draft=(await result(await entries.POST(req('/api/entries','POST',capsule)),201)).entry;
 const attachment=(await result(await assets.POST(req('/api/assets','POST',png,{'content-type':'image/png','x-parent-type':'capsule','x-parent-id':draft.id,'x-asset-purpose':'attachment'})),201)).asset;
 const sealed=(await result(await entries.PATCH(req('/api/entries','PATCH',{...draft,data:{...draft.data,stage:'sealed'}})))).entry;assert.equal(sealed.locked,true);assert.equal(sealed.data.body,'');checks+=2;
 const listed=(await result(await entries.GET(req('/api/entries')))).entries.find(e=>e.id===draft.id);assert.equal(listed.data.body,'');checks++;
 assert.equal((await result(await assets.GET(req('/api/assets?parentId='+draft.id)))).assets.length,0);checks++;
 const attachCtx={params:Promise.resolve({id:attachment.id})};await result(await asset.GET(req('/api/assets/'+attachment.id),attachCtx),423);
 await result(await entries.PATCH(req('/api/entries','PATCH',{...sealed,data:{...sealed.data,stage:'draft'}})),409);
 await result(await assets.POST(req('/api/assets','POST',png,{'content-type':'image/png','x-parent-type':'capsule','x-parent-id':draft.id,'x-asset-purpose':'attachment'})),409);
 await result(await asset.DELETE(req('/api/assets/'+attachment.id,'DELETE'),attachCtx),409);
 const open=(await result(await entries.POST(req('/api/entries','POST',{...capsule,id:crypto.randomUUID(),data:{...capsule.data,stage:'sealed',unlockAt:'2020-01-01T00:00:00.000Z'}})),201)).entry;assert.equal(open.locked,false);assert.equal(open.data.body,capsule.data.body);checks+=2;
 await result(await backup.POST(req('/api/backup','POST',{})),400);
 const full=await result(await backup.POST(req('/api/backup','POST',{confirmFullArchive:true})));assert.equal(full.entries.find(e=>e.id===draft.id).data.body,capsule.data.body);assert(full.assets.some(a=>a.id===original.id));assert(full.assets.some(a=>a.id===attachment.id));checks+=3;
 assert.equal(full.entries.find(e=>e.id===editedNickname.id).data.origin,'The origin, amended.');assert.equal(full.entries.find(e=>e.id===savedNicknameB.id).data.funnyMoment,nicknameB.data.funnyMoment);checks+=2;
 const exported=await asset.GET(req('/api/assets/'+attachment.id+'?export='+full.exportToken),attachCtx);assert.equal(exported.status,200);assert.deepEqual(new Uint8Array(await exported.arrayBuffer()),png);checks+=2;
 await result(await asset.GET(req('/api/assets/'+attachment.id+'?export='+full.exportToken,'GET',undefined,{'oai-authenticated-user-id':'different-viewer'}),attachCtx),423);
 await DB.prepare('UPDATE export_tickets SET expires_at=? WHERE id=?').bind('2000-01-01',full.exportToken).run();await result(await asset.GET(req('/api/assets/'+attachment.id+'?export='+full.exportToken),attachCtx),423);
 assert.equal(planner.addMonths('2027-01-31',1),'2027-02-28');assert.equal(planner.addMonths('2028-01-31',1),'2028-02-29');checks+=2;
 const plan={...planner.blankPlan(),startDate:'2026-09-10',targetDate:'2027-09-10',budget:10000,saved:2000,monthlySaving:500};plan.milestones=planner.buildMilestones(plan,[{...item,status:'Dreaming',dueDate:'2027-05-01',currency:'CAD',budget:200}]);assert.equal(plan.milestones.length,14);assert.equal(plan.milestones.find(m=>m.wishId===item.id).date,'2027-05-01');assert.equal(planner.planBudget(plan).gap,2000);checks+=3;
 await result(await entries.POST(req('/api/entries','POST',{id:crypto.randomUUID(),kind:'plan',data:plan})),201);
 await result(await entries.POST(req('/api/entries','POST',{id:crypto.randomUUID(),kind:'plan',data:{...plan,targetDate:'2025-01-01'}})),400);

 // Phase 1 replaces insecure public-archive expectations with explicit denial.
 // PUBLIC_READ is ignored for private reads; only quiz POST remains public.
 globalThis.__giftTestEnv.PUBLIC_READ='true';
 globalThis.__giftTestEnv.EDITOR_EMAILS='bounniecrisis@gmail.com,changyue960915@gmail.com';
 const anonymous=(path,method='GET',data)=>new Request('https://gift.test'+path,{method,headers:{'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});
 await result(await photos.GET(anonymous('/api/photos')),401);
 await result(await wishes.GET(anonymous('/api/wishes')),401);
 await result(await journey.GET(anonymous('/api/journey')),401);
 const guestAnswer=await result(await journey.POST(anonymous('/api/journey','POST',{index:0,answer:'Vistopia'})));assert.equal(guestAnswer.correct,true);assert.equal(guestAnswer.temporary,true);checks+=2;
 assert.equal((await result(await journey.GET(req('/api/journey')))).unlocked,6);checks++;
 await result(await photos.POST(anonymous('/api/photos','POST',{})),401);
 await result(await entries.POST(req('/api/entries','POST',nicknameA,{'oai-authenticated-user-email':'stranger@example.test'})),403);
 await result(await wishes.DELETE(req('/api/wishes','DELETE',{}, {'oai-authenticated-user-email':'stranger@example.test'})),403);
 await result(await backup.POST(anonymous('/api/backup','POST',{confirmFullArchive:true})),401);
 await result(await backup.POST(req('/api/backup','POST',{confirmFullArchive:true},{'oai-authenticated-user-email':'stranger@example.test'})),403);
 const privateDraft=(await result(await entries.POST(req('/api/entries','POST',{...capsule,id:crypto.randomUUID(),data:{...capsule.data,title:'An unfinished draft'}})),201)).entry;
 const privateAsset=(await result(await assets.POST(req('/api/assets','POST',png,{'content-type':'image/png','x-parent-type':'capsule','x-parent-id':privateDraft.id,'x-asset-purpose':'attachment'})),201)).asset;
 await result(await entries.GET(anonymous('/api/entries')),401);
 const memberEntries=(await result(await entries.GET(req('/api/entries')))).entries;
 assert(memberEntries.some(e=>e.id===privateDraft.id));assert.equal(memberEntries.find(e=>e.id===sealed.id).data.body,'');checks+=2;
 await result(await assets.GET(anonymous('/api/assets?parentId='+privateDraft.id)),401);
 await result(await asset.GET(anonymous('/api/assets/'+privateAsset.id),{params:Promise.resolve({id:privateAsset.id})}),401);
 await result(await asset.GET(anonymous('/api/assets/'+attachment.id+'?export='+full.exportToken),attachCtx),401);
 await result(await media.GET(anonymous('/api/media/'+saved.id),context),401);
 globalThis.__giftTestEnv.PUBLIC_READ='false';
 await result(await photos.GET(anonymous('/api/photos')),401);
 delete globalThis.__giftTestEnv.PUBLIC_READ;
 const {checkPrivacy}=await import('./check-privacy.mjs');
 checks+=await checkPrivacy({DB,BUCKET,photos,photo,media,wishes,entries,assets,asset,journey,backup,photoId:saved.id,voiceId:voice.id,originalId:original.id,lockedAssetId:attachment.id,lockedId:sealed.id,openId:open.id,draftId:privateDraft.id,draftAssetId:privateAsset.id,png,audioBytes});
 await result(await entries.DELETE(req('/api/entries','DELETE',{id:sealed.id,revision:sealed.revision})));
 await result(await asset.GET(req('/api/assets/'+attachment.id),attachCtx),404);
 const currentPhoto=(await result(await photos.GET(req('/api/photos')))).photos.find(p=>p.id===saved.id);
 await result(await photo.DELETE(req('/api/photos/'+saved.id+'?revision='+currentPhoto.revision,'DELETE'),context));
 assert.equal((await result(await assets.GET(req('/api/assets?parentId='+saved.id)))).assets.length,0);checks++;
 await result(await asset.GET(req('/api/assets/'+voice.id),voiceCtx),404);
 await result(await entries.DELETE(req('/api/entries','DELETE',{id:editedNickname.id,revision:editedNickname.revision})));
 assert.equal((await result(await entries.GET(req('/api/entries')))).entries.some(e=>e.id===editedNickname.id),false);checks++;
 const latestWish=(await result(await wishes.GET(req('/api/wishes')))).wishes[0];
 await result(await wishes.DELETE(req('/api/wishes','DELETE',{id:latestWish.id,revision:latestWish.revision})));

 assert.equal((await result(await wishes.GET(req('/api/wishes')))).wishes.length,0);checks++;
 const {checkClientPrivacy}=await import('./check-client-privacy.mjs');
 checks+=await checkClientPrivacy();
 console.log(`PASS: ${checks} checks covering V3/V4 continuity, V5 wish-to-memory transactions, independent perspectives and collections, future-letter locks, attachment access, full-export authorization, HEIC originals, timeline planning, shared nickname stories, validation and revision conflicts.`);
}finally{await mf.dispose();await rm(dir,{recursive:true,force:true});delete globalThis.__giftTestEnv;}
